version: "3"

networks:
  laravel:

services:
  php:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    tty: true
    restart: unless-stopped
    networks:
      - laravel
    environment:
      - DB_CONNECTION=db_rw
      - DB_HOST=mysql
      - TZ=${TZ}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
      - PHP_VERSION=${PHP_VERSION:-7.3}
      - WITH_XDEBUG=${WITH_XDEBUG:-0}
      - GIT_USER=${GIT_USER}
      - GIT_EMAIL=${GIT_EMAIL}
      - SERVICE_NAME=php
      - SERVICE_TAGS=dev

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    networks:
      - laravel

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-store:/data
    networks:
      - laravel

volumes:
  redis-store:
