version: "3"

networks:
  laravel:

services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/var/www:delegated
      - ./docker/php/psysh:/root/.config/psysh
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    tty: true
    restart: unless-stopped
    networks:
      - laravel
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - TZ=${TZ}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - QUEUE_DRIVER=${QUEUE_DRIVER}
      - REDIS_HOST=redis
      - PHP_VERSION=${PHP_VERSION:-7.3}
      - WITH_XDEBUG=${WITH_XDEBUG:-0}
      - GIT_USER=${GIT_USER}
      - GIT_EMAIL=${GIT_EMAIL}
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/var/www:delegated
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    networks:
      - laravel

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql:delegated
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data:delegated
    networks:
      - laravel

volumes:
  redis-store:
